apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cameratrap-detection-sync
spec:
  hosts:
  - "*"
  gateways:
  - ai4e-gateway
  http:
  - match:
    - uri:
        prefix: ""
    route:
    - destination:
        host: cameratrap-detection-sync.default.svc.cluster.local
        port:
          number: 1212
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-cameratrap-detection-sync
spec:
  host: cameratrap-detection-sync.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
